# ARM XXX obj-$(CONFIG_STING) += dwarf-read.o
# ARM XXX obj-$(CONFIG_STING) += dwarf-cfi.o
# ARM XXX obj-$(CONFIG_STING) += dwarf-expression.o
# ARM XXX obj-$(CONFIG_STING) += dwarf-fde.o
obj-$(CONFIG_STING) += user_unwind.o
